Intro_to_software_project1/Olamide/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from frontend import views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url

urlpatterns = [
    path('', views.index, name='index'),
    path('pages/', include('frontend.urls')),
    path('backend/', include('backend.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Intro_to_software_project1/backend/urls.py
from django.urls import path
from django.conf.urls import url 
from backend import views

app_name = 'backend'

urlpatterns = [
    path('', views.login_view, name='login_view'),
    path('home/', views.dash, name='dash'),
    path('register-page/', views.register_form, name='register_form'),
]

Intro_to_software_project1/frontend/urls.py
from django.urls import path
from django.conf.urls import url 
from frontend import views

app_name = 'frontend'

urlpatterns = [
    path('backend/', views.home, name='home'),
]

Intro_to_software_project1/backend/models.py
from django.db import models

# Create your models here.

Intro_to_software_project1/backend/forms.py
from django import forms
from django.core import validators
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordChangeForm




class RegisterForm(UserCreationForm):
    first_name = forms.CharField(required=False, widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter Firstname'}))
    last_name = forms.CharField(required=False, widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter Lastname'}))
    username = forms.IntegerField(label='Student Id', widget=forms.NumberInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter Student Id'}))
    email = forms.EmailField(label='Email', widget=forms.EmailInput
        (attrs={'class': 'form-control', 'placeholder': 'Enter Student E-mail'}))
    password1 = forms.CharField(label='Enter Password', widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter Password'}))
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter Password'}))

        
    def clean_email(self):
        email_field = self.cleaned_data.get('email')
        if User.objects.filter(email=email_field).exists():
            raise forms.ValidationError('Email already exist')
        return email_field

    class Meta():
        model = User
        fields = [ 'first_name','last_name','username', 'email', 'password1', 'password2']

    def save(self, commit=True):
        user = super().save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.username = self.cleaned_data['username']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()
            return user

Intro_to_software_project1/backend/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.core import mail
from django.views.generic import ListView

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic.edit import UpdateView 
from backend.forms import *
from django.contrib import messages
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_text
from django.contrib.auth.models import User
from django.db import IntegrityError

# Create your views here.




def register_form(request):
    if request.method == 'POST':
        register_form = RegisterForm(request.POST)
        if register_form.is_valid():
            register_form.save()
            messages.success(request, 'User Registered')
    else:
        register_form = RegisterForm()
    return render(request, 'frontend/signup.html', {'reg': register_form})

def login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('backend:dash')
        else:
            messages.error(request, 'Username and Password do not match')
    return render(request, 'frontend/login.html')

def dash (request):
    return render(request, 'frontend/home.html')

Intro_to_software_project1/frontend/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from frontend.models import *
# from django.contrib.auth.models import User
# from django.core.exceptions import ObjectDoesNotExist
# from backend.forms import *

# Create your views here.


def index(request):
    return render(request, 'frontend/index.html')

def home (request):
    return render(request, 'frontend/home.html')

Intro_to_software_project1/templates/frontend/home.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <title>
      Home
      
    </title>
  </head>
  <body>
  
<h1>Welcome to your Dashboard  </h1>
    </body>
</html>

Intro_to_software_project1/templates/frontend/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'public/style.css' %}">
    <link rel="stylesheet" href="{% static 'public/bootstrap.min.css' %}">
    <title>Document</title>
</head>
<body>
    

    
       <h1> Wud u like to <a href="{% url 'backend:login_view'%}">login</a> to into ur portal 

       </h1>

       <script src="{% static 'public/jquery.js' %}"></script>
       <script src="{% static 'public/main.js' %}"></script>

</body>
</html>

Intro_to_software_project1/templates/frontend/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'public/style.css' %}">
    <link rel="stylesheet" href="{% static 'public/bootstrap.min.css' %}">
    <title>Document</title>
</head>
<body>
    

    
       <aside>
        <form action="#" method='post' class="form m-5">

            
            <div class="w-50 mx-auto">
                <br><br>
                <h3 class="spec head" >Engineering School</h3>
                <br>
                <div class="form-group">
                    <!-- <form action="" method="get"></form> -->
                    <input type="number" name="username" placeholder="Username" class="form-control" placeholder="Enter Student Id">
                </div>

                <div class="form-group">
                    <!-- <form action="" method="get"></form> -->
                    <input type="password" name="password" placeholder="Password" class="form-control" placeholder="Enter password">
                </div>

                <button type="submit" class=" abutton " id="abutton">login</button>
                <div class="signup">
                    <p class="text">Don't have an account?? <br> <a href="{%url 'backend:register_form' %}" class="spec"> sign up </a> here <br><br> </p>
                </div>
            </div>
            {% csrf_token %}
           </form>
           
       </aside>

       <script src="{% static 'public/jquery.js' %}"></script>
       <script src="{% static 'public/main.js' %}"></script>

</body>
</html>

Intro_to_software_project1/templates/frontend/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'public/style.css' %}">
    <link rel="stylesheet" href="{% static 'public/bootstrap.min.css' %}">
    <title>Document</title>
</head>
<body style="padding-top:30px;">
    

<div class="container">
  <aside style=" padding-top:30px;">
  <form action="#" method="post" class="m-5">
  <div>
  <h3 style=" margin-left:20px; color:#ffff !important;">Sign Up</h3>
  </div>
      {% if messages %}
        {% for mes in messages %}
          <div class="alert alert-success">{{ mes }}</div>
        {% endfor %}
      {% endif %}
      {{ reg }}
      <div id="pass-info" class="clearfix"></div>
      <div style="padding-top: 20px; padding-bottom:20px;">
        <input type="submit" class="btn btn-danger" class="btn_1 rounded full-width add_top_30 text-center" value="Register" 
        style="margin-left: 10px; padding-top: 40px; padding: 10px; font-size: 20px; border-radius:20px; width: 150px;"> Already have an account ? <a href="{% url 'backend:login_view'%}">Sign in</a>
      </div>
      {% csrf_token %}
  </form>
           
</aside>
</div>


       <script src="{% static 'public/jquery.js' %}"></script>
       <script src="{% static 'public/main.js' %}"></script>

</body>
</html>